= Инструкции для работы в команде

Настоящая инструкция предназначена для создания у участников общего представления о том, как будет осуществляться командная работа, а также чтобы дать рекомендации, как правильно вести репозиторий, чтобы сохранялся единый стиль оформления.

== Общие правила ведения репозитория и решения задач

Общие правила ведения репозитория:

 * Делайте коммиты после каждого **значительного** изменения.
 * Пишите коммиты на английском языке, а не на русском!
 * Пишите коммиты с заглавной буквы. Исключение могут составлять коммиты, которые, например, начинаются с названия функции `Commit: "stringParser() was created"`.

Общие правила написания кода:

 * Если необходимо добавить несколько однотипных файлов, решающих общую задачу, добавляйте их в отдельную папку. 
 Примером может послужить папка __disConNormForm__ (путь: `/src/js/func`). Можно заметить, что в ней находится несколько файлов .js, в связи с тем, что все они отвечают за одну задачу: логику на странице __disConNormForm.html__.
 * Перед тем, как писать решение на JS, ознакомьтесь с файлами, подключенными к вашей странице .html. Может оказаться, что вы случайно дадите функциям одинаковое название. Будьте внимательны!
 * Старайтесь писать комментарии (однострочные или многострочные -- на ваше усмотрение) к вашему коду (хотя бы описывайте кратко, что делает та или иная функция). Это поможет другим участникам и вам самим лучше ориентироваться в коде и понимать его логику.

== Общая логика работы

Примерная картина работы в репозитории следующая: для каждой подзадачи (будь то разработка таблицы истинности, парсинг или любая другая) будет создана отдельная ветка в репозитории. 
Каждый из участников работает в своей ветке, делая коммиты в неё соотвественно. 
**После того, как ваша подзадача будет уже в более-менее рабочем состоянии, ваша ветка будет объединена с главной и все участники проекта должны будут обновить свои локальные репозитории**. 
Ветка будет объединяться с главной после каждых существенных изменений (когда появится необходимость в слиянии вашей ветки с главной, вы можете сообщить мне об этом лично или во Вконтакте).

== Какие задачи необходимо выполнить?

=== 23.04.2019

==== Лиза

Необходимо разработать алгоритм создания таблицы истинности на основе дерева синтаксического разбора. 
Для решения этой задачи в репозитории уже создан шаблон страницы __truthTable.html__ (путь: `src/html/func`), к которой подключены необходимые js-файлы. 

Особое внимание следует обратить на файлы __main.js__ и __truthTable.js__ (путь: `src/js/func/truthTable`). 

В __main.js__ расположен код, отвечающий за общую логику на странице. 
На данный момент, например, там реализовано получение введённого пользователем выражения в строку с последующей отправкой её в функцию __getTruthTable()__, 
которая в результате своей работы должна записать в переменную truthTable массив Y[ ], который сайту как раз и необходимо отобразить.

В __truthTable.js__ расположен код, отвечающий за создание массива истинности. 
На данный момент там присутствует лишь функция __getTruthTable()__, принимающая на вход строку и превращающая её в дерево синтаксического разбора.
Таким образом, необходимо дописать необходимые функции, которые будут обрабатывать это дерево и строить на его основе массив.

==== Настя

Необходимо разработать алгоритм минимизации картами Карно на основе массива Y[ ] (позже этот массив будет взят из соответствующей функции, реализованной Лизой). 
Для решения этой задачи в репозитории уже создан шаблон страницы __karnaughMap.html__ (путь: `src/html/func`), к которой подключены необходимые js-файлы. 

Особое внимание следует обратить на файлы __main.js__ и __karnaughMap.js__ (путь: `src/js/func/karnaughMap`). 

В __main.js__ расположен код, отвечающий за общую логику на странице. 
На данный момент, например, там реализовано получение введённого пользователем выражения в строку с последующей отправкой её в функцию __createKarnaughMap()__, 
которая в результате своей работы должна получить таблицу с минимизацией и итоговую минимизированную функцию. 
Можно заметить, что функция __createKarnaughMap()__ не возвращает никакого результата (отсутствует __return__). 
Поэтому необходимо реализовать возврат значений (любым удобным образом).

В __karnaughMap.js__ расположен код, отвечающий за минимизацию картами Карно. 
На данный момент там присутствует лишь функция __createKarnaughMap()__, принимающая на вход строку и перенаправляющая её в функцию __getTruthTable()__, которую должна написать Лиза.
Пока Лиза не сделала этого, можешь закомментировать эту строчку и создать свой тестовый массив типа: [1, 0, 0, 1, 1, ...].
Таким образом, необходимо дописать необходимые функции, которые будут обрабатывать массив Y[ ],выполняя его минимизацию.

==== Никита

Необходимо разработать алгоритм построения ДНФ и КНФ на основе дерева синтаксического разбора. 
Для решения этой задачи в репозитории уже создан шаблон страницы __disConNormForm.html__ (путь: `src/html/func`), к которой подключены необходимые js-файлы. 

Особое внимание следует обратить на файлы __main.js__ и __disConNormForm.js__ (путь: `src/js/func/disConNormForm`). 

В __main.js__ расположен код, отвечающий за общую логику на странице. 
На данный момент, например, там реализовано получение введённого пользователем выражения в строку с последующей отправкой её в функции __getDisNormForm()__ и __getConNormForm()__, 
которые в результате своей работы должны вернуть ДНФ и КНФ соответсвенно.
Желательно реализовать также и вывод решения по действиям (например, при нажатии на соответсвующую кнопку на странице __disConNormForm.html__).

В __disConNormForm.js__ расположен код, отвечающий за получение ДНФ и КНФ. 
На данный момент там присутствуют лишь функции __getDisNormForm()__ и __getConNormForm()__, принимающие на вход строку и превращающие её в дерево синтаксического разбора.
Таким образом, необходимо дописать необходимые функции, которые будут обрабатывать это дерево и строить на его основе ДНФ и КНФ.

== Важные замечания

Для удобной отладки программ в проект была добавлена папка __test__, расположенная в корневом каталоге. 
Вам необходимо создать там файлы, тестирующие функции калькулятора, которые вы разрабатываете. 
Таким образом, добавлять тесты для файлов __main.js__ не нужно, а только для файлов __truthTable.js__, __karnaughMap.js__ и __disConNormForm.js__. 
Рекомендуемые названия для файлов -- __truthTableTest.js__, __karnaughMapTest.js__ и __disConNormFormTest.js__ соответственно.
В них необходимо написать тесты хотя бы к самым главным функциям (__getTruthTable()__ для Лизы, __createKarnaughMap()__ для Насти, __getDisNormForm()__ и __getConNormForm()__ для Никиты). 
После добавления файла в каталог __test__, не забудьте подключить его к вашей странице .html на время написания кода. 

**Отнеситесь к написанию тестов ответственно, так как это поможет в первую очередь вам самим для удобной отладки, а впоследствии тестерам (после завершения проекта)!**
